# cmake project based settings
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/install")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake")
set(CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}/install")
set(CMAKE_INSTALL_RPATH "${CMAKE_BINARY_DIR}/lib")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

set(deps_dir "${CMAKE_SOURCE_DIR}/deps_party")
set(third_dir "${CMAKE_SOURCE_DIR}/third_party")
set(modules_dir "${CMAKE_SOURCE_DIR}/modules")
set(samples_dir "${CMAKE_SOURCE_DIR}/samples")

list(APPEND CMAKE_PREFIX_PATH "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
file(GLOB deps_party_folders LIST_DIRECTORIES true "${deps_dir}/*")
foreach(dir ${deps_party_folders})
    list(APPEND CMAKE_PREFIX_PATH ${dir})
endforeach()
message(STATUS "CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")

macro(auto_add_all_subdirectory)
    file(GLOB sub_dirs LIST_DIRECTORIES true ${CMAKE_CURRENT_SOURCE_DIR}/*)
    foreach(dir ${sub_dirs})
         if(IS_DIRECTORY ${dir} AND EXISTS "${dir}/CMakeLists.txt")
            add_subdirectory(${dir})
        endif()
    endforeach()
endmacro(auto_add_all_subdirectory)

macro(set_cxx_compile_options target_name)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:MSVC>>:/utf-8>)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:MSVC>>:/Zc:preprocessor>)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:MSVC>>:/std:c++20>)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:MSVC>>:/Zi>)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:GNU,Clang>>:-finput-charset=UTF-8>)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:GNU,Clang>>:-fexec-charset=UTF-8>)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:GNU,Clang>>:-g>)
endmacro(set_cxx_compile_options)

macro(set_cuda_compile_options target_name)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:MSVC>>:-Xcompiler=/utf-8>)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:MSVC>>:-Xcompiler=/std:c++20>)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:MSVC>>:-Xcompiler=/Zc:preprocessor>)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:GNU,Clang>>:-Xcompiler=-std=c++20>)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:GNU,Clang>>:-Xcompiler=-finput-charset=UTF-8>)
    target_compile_options(${target_name} PRIVATE $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:GNU,Clang>>:-Xcompiler=-fexec-charset=UTF-8>)
endmacro(set_cuda_compile_options)
